default_language_version:
    python: python3.10
exclude: '\.ref$'
repos:
  # - repo: https://github.com/python/black.git
  #   rev: 22.8.0
  #   hooks:
  #     - id: black
  - repo: https://github.com/john-hen/Flake8-pyproject
    rev: 1.1.0
    hooks:
      - id: Flake8-pyproject
        additional_dependencies:
          - flake8-black>=0.1.1
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: text-unicode-replacement-char
